# Generated by Django 4.1.7 on 2023-03-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Last Name')),
                ('distinction', models.CharField(blank=True, max_length=50, verbose_name='Distinction')),
                ('note', models.TextField(blank=True, max_length=500, verbose_name='description')),
            ],
        ),
    ]
