name: build
on:
  push:
    branches:
      - main
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - run: mkdocs gh-deploy -b gh-pages --config-file ../mkdocs.yml -d docs