name: build
on:
  push:
    branches:
      - main
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up the environment
        uses: ./.github/actions/setup-poetry-env

      - name: Check if documentation can be built
        run: poetry run mkdocs build -s

      - run: poetry run mkdocs gh-deploy --config-file ../mkdocs.yml